import Link from "next/link";
import { ArrowRight, BadgeCheck, ClipboardList, FileCheck2, Gauge } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export default function MerchantsPage(){
  return <><Header/><main>
    <section className="page-hero"><div className="shell"><div className="eyebrow">COMMERCIANTI</div><h1>Più fiducia sull'auto che stai vendendo.</h1><p className="lead">Porta la verifica VeriDrive dentro il percorso di vendita e dai al cliente un risultato chiaro, digitale e verificabile.</p><Link className="button" href="/prenota">Richiedi una verifica <ArrowRight size={18}/></Link></div></section>
    <section><div className="shell"><div className="proof-grid"><div><div className="eyebrow">PERCHÉ USARLO</div><h2>Trasforma la verifica in un elemento della vendita.</h2><p className="lead">Il commerciante può utilizzare il risultato della verifica come supporto informativo per la vettura e condividerne il certificato con il cliente.</p></div><div className="proof-cards"><div className="mini-card"><ClipboardList/><strong>Verifica organizzata</strong><span>Richiedi il controllo per il veicolo e segui il percorso digitale.</span></div><div className="mini-card"><Gauge/><strong>VeriScore</strong><span>Un punteggio sintetico che rende il risultato immediatamente leggibile.</span></div><div className="mini-card"><FileCheck2/><strong>Certificato digitale</strong><span>Condividi il risultato previsto dal servizio acquistato.</span></div><div className="mini-card"><BadgeCheck/><strong>Più trasparenza</strong><span>Una verifica esterna aggiunge informazioni utili alla decisione del cliente.</span></div></div></div></div></section>
    <section className="panel-section"><div className="shell"><div className="eyebrow">PERCORSO</div><h2>Tre passaggi.</h2><div className="steps"><div className="step"><div className="step-number">01</div><h3>Individua il veicolo</h3><p>Inserisci i dati dell'auto nel percorso di prenotazione.</p></div><div className="step"><div className="step-number">02</div><h3>Organizza la verifica</h3><p>VeriDrive gestisce il controllo secondo il servizio scelto.</p></div><div className="step"><div className="step-number">03</div><h3>Condividi il risultato</h3><p>Il cliente può consultare il risultato e il certificato digitale quando previsto.</p></div></div></div></section>
    <section><div className="shell cta-panel"><div><div className="eyebrow">PROVA IL PERCORSO</div><h2>Una verifica chiara aiuta a vendere con più fiducia.</h2></div><Link className="button" href="/prenota">Prenota una verifica <ArrowRight size={18}/></Link></div></section>
  </main><Footer/></>;
}
