import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createServiceClient } from "@/lib/supabase/service";
import { jsPDF } from "jspdf";
import QRCode from "qrcode";

function rgb(hex: string): [number, number, number] { const h=hex.replace("#",""); return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]; }
function theme(score:number){ if(score>=80)return{main:"#16a34a",pale:"#dcfce7",label:"OTTIMO"}; if(score>=60)return{main:"#eab308",pale:"#fef9c3",label:"BUONO"}; return{main:"#dc2626",pale:"#fee2e2",label:"CRITICITÀ"}; }
function drawGauge(pdf:jsPDF,cx:number,cy:number,score:number){ const t=theme(score),m=rgb(t.main),p=rgb(t.pale),r=21; pdf.setFillColor(...p); pdf.circle(cx,cy,r,"F"); pdf.setDrawColor(226,232,240); pdf.setLineWidth(4); pdf.circle(cx,cy,r-3,"S"); pdf.setDrawColor(...m); const end=-Math.PI/2+Math.PI*2*score/100; for(let i=0;i<Math.ceil(44*score/100);i++){const a1=-Math.PI/2+Math.PI*2*i/44;const a2=Math.min(end,-Math.PI/2+Math.PI*2*(i+.72)/44); if(a2<=a1)continue; pdf.setLineWidth(2.6);pdf.line(cx+(r-3)*Math.cos(a1),cy+(r-3)*Math.sin(a1),cx+(r-3)*Math.cos(a2),cy+(r-3)*Math.sin(a2));} pdf.setFillColor(255,255,255);pdf.circle(cx,cy,r-8,"F");pdf.setTextColor(...rgb("#17233c"));pdf.setFont("helvetica","bold");pdf.setFontSize(18);pdf.text(String(score),cx,cy+2,{align:"center"});pdf.setFont("helvetica","normal");pdf.setFontSize(6.5);pdf.text("VERISCORE",cx,cy+8,{align:"center"});pdf.setTextColor(...m);pdf.setFont("helvetica","bold");pdf.setFontSize(7);pdf.text(t.label,cx,cy+r+7,{align:"center"}); }
function getChecklist(value:unknown){try{const p=typeof value==="string"?JSON.parse(value):value;return Array.isArray(p?.checklist)?p.checklist:[]}catch{return[]}}
function groupsOf(checklist:unknown){const out=new Map<string,{ok:number,total:number}>();for(const r of Array.isArray(checklist)?checklist:[]){const i=r as{area?:string;result?:string|null};const a=i.area||"Altro";const g=out.get(a)||{ok:0,total:0};g.total++;if(i.result==="ok")g.ok++;out.set(a,g)}return[...out.entries()].map(([area,g])=>({area,...g,pct:g.total?Math.round(g.ok/g.total*100):0}))}
async function imageData(db:ReturnType<typeof createServiceClient>,path:string){const {data:s}=await db.storage.from("inspection-photos").createSignedUrl(path,300);if(!s?.signedUrl)return null;try{const r=await fetch(s.signedUrl);if(!r.ok)return null;const b=new Uint8Array(await r.arrayBuffer());let x="";for(let i=0;i<b.length;i+=0x8000)x+=String.fromCharCode(...b.subarray(i,i+0x8000));const ct=r.headers.get("content-type")||"image/jpeg";return{data:`data:${ct};base64,${btoa(x)}`,format:ct.includes("png")?"PNG":"JPEG"}}catch{return null}}

export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){try{const{id}=await params;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Accesso richiesto."},{status:401});const db=createServiceClient();const{data:customer}=await db.from("customers").select("id").eq("auth_id",user.id).maybeSingle();if(!customer)return NextResponse.json({error:"Profilo cliente non disponibile."},{status:403});const{data:certificate,error:ce}=await db.from("veriscore_certificates").select("id,booking_id,public_code,vehicle_plate,vehicle_vin,vehicle_make,vehicle_model,vehicle_year,vehicle_mileage,veriscore,workshop_id,issued_at").eq("id",id).maybeSingle();if(ce)return NextResponse.json({error:ce.message},{status:500});if(!certificate)return NextResponse.json({error:"Certificato non trovato."},{status:404});const{data:booking}=await db.from("bookings").select("id,customer_id,service,overall_notes").eq("id",certificate.booking_id).eq("customer_id",customer.id).maybeSingle();if(!booking)return NextResponse.json({error:"Certificato non associato al cliente."},{status:404});const{data:workshop}=await db.from("workshops").select("name,city,postal_code").eq("id",certificate.workshop_id).maybeSingle();const plus=booking.service==="veriscore_plus";const groups=groupsOf(getChecklist(booking.overall_notes));let inspectionId:string|null=null;if(plus){const{data:i}=await db.from("inspections").select("id").eq("booking_id",certificate.booking_id).maybeSingle();inspectionId=i?.id??null}const{data:photos}=plus&&inspectionId?await db.from("photos").select("id,storage_path,caption,check_id,created_at").eq("inspection_id",inspectionId).order("created_at",{ascending:true}).limit(10):{data:[] as Record<string,unknown>[]};
const pdf=new jsPDF({unit:"mm",format:"a4"}),W=pdf.internal.pageSize.getWidth(),H=pdf.internal.pageSize.getHeight(),navy=rgb("#0b1f3a"),blue=rgb("#2563eb"),cyan=rgb("#38bdf8"),pale=rgb("#eef5ff"),text=rgb("#17233c"),muted=rgb("#64748b");
pdf.setFillColor(...navy);pdf.rect(0,0,W,43,"F");pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(28);pdf.text("VeriDrive",18,19);pdf.setFont("helvetica","normal");pdf.setFontSize(10);pdf.setTextColor(210,225,255);pdf.text(plus?"CERTIFICATO VERISCORE PLUS":"CERTIFICATO VERISCORE",18,29);pdf.setFillColor(...blue);pdf.roundedRect(W-77,8,59,27,6,6,"F");pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(18);pdf.text(`${certificate.veriscore}/100`,W-47,20,{align:"center"});pdf.setFontSize(7);pdf.text("VERISCORE",W-47,28,{align:"center"});
pdf.setTextColor(...muted);pdf.setFont("helvetica","normal");pdf.setFontSize(9);pdf.text("CERTIFICATO UFFICIALE",18,55);pdf.setTextColor(...text);pdf.setFont("helvetica","bold");pdf.setFontSize(21);pdf.text(String(certificate.public_code),18,67);drawGauge(pdf,W-42,64,Number(certificate.veriscore));
pdf.setFillColor(...pale);pdf.roundedRect(16,80,W-32,58,7,7,"F");pdf.setTextColor(...text);pdf.setFont("helvetica","bold");pdf.setFontSize(11);pdf.text("DATI DEL VEICOLO",22,91);const d=[['Veicolo',[certificate.vehicle_make,certificate.vehicle_model].filter(Boolean).join(" ")||"Non indicato"],['Anno',String(certificate.vehicle_year??"Non indicato")],['Targa',String(certificate.vehicle_plate)],['VIN / Telaio',String(certificate.vehicle_vin)],['Chilometraggio',`${Number(certificate.vehicle_mileage).toLocaleString("it-IT")} km`],['Officina',workshop?.name??"Officina VeriDrive"]];d.forEach(([l,v],i)=>{const x=i%2===0?22:W/2+2,y=101+Math.floor(i/2)*12;pdf.setTextColor(...muted);pdf.setFont("helvetica","normal");pdf.setFontSize(8);pdf.text(String(l),x,y);pdf.setTextColor(...text);pdf.setFont("helvetica","bold");pdf.setFontSize(9.5);pdf.text(String(v),x,y+5,{maxWidth:74})});
pdf.setFillColor(...cyan);pdf.roundedRect(16,149,W-32,14,5,5,"F");pdf.setTextColor(...navy);pdf.setFont("helvetica","bold");pdf.setFontSize(10);pdf.text(plus?"VERISCORE PLUS · VERIFICA + DOCUMENTAZIONE":"VERIFICA TECNICA CERTIFICATA",22,158.5);pdf.setTextColor(...text);pdf.setFont("helvetica","normal");pdf.setFontSize(10);pdf.text(pdf.splitTextToSize(plus?"Certificato con verifica tecnica completa e documentazione fotografica raccolta dall'officina.":"Certificato del risultato della verifica tecnica eseguita dall'officina aderente a VeriDrive.",W-44),22,176);pdf.setTextColor(...muted);pdf.setFontSize(9);pdf.text(`Data emissione: ${new Intl.DateTimeFormat("it-IT",{day:"2-digit",month:"2-digit",year:"numeric"}).format(new Date(certificate.issued_at))}`,22,194);
pdf.setFillColor(...navy);pdf.roundedRect(16,H-28,W-32,16,5,5,"F");pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(8);pdf.text("VERIFICA PUBBLICA",22,H-18);pdf.setFont("helvetica","normal");pdf.text(`veridrive.it/verifica/${certificate.public_code}`,60,H-18);const qr=await QRCode.toDataURL(`${process.env.NEXT_PUBLIC_APP_URL??"https://veridrive.it"}/verifica/${encodeURIComponent(String(certificate.public_code))}`,{margin:1,width:256});pdf.addImage(qr,"PNG",W-54,H-67,38,38);pdf.setTextColor(...navy);pdf.setFont("helvetica","bold");pdf.setFontSize(6.2);pdf.text("SCANSIONA PER VERIFICARE",W-35,H-25,{align:"center"});
pdf.addPage();pdf.setFillColor(...navy);pdf.rect(0,0,W,34,"F");pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(21);pdf.text("VeriDrive",18,15);pdf.setFont("helvetica","normal");pdf.setFontSize(9.5);pdf.text(plus?"VERISCORE PLUS · SCHEDA TECNICA E FOTO":"VERISCORE · SCHEDA TECNICA",18,24);pdf.setTextColor(...text);pdf.setFont("helvetica","bold");pdf.setFontSize(15);pdf.text("Punteggi per area",18,48);let y=60;for(const g of groups.slice(0,5)){const t=theme(g.pct);pdf.setFillColor(...rgb(t.pale));pdf.roundedRect(18,y,W-36,16,5,5,"F");pdf.setTextColor(...text);pdf.setFont("helvetica","bold");pdf.setFontSize(9.5);pdf.text(g.area,24,y+10.5);pdf.setFont("helvetica","normal");pdf.text(`${g.ok}/${g.total}`,W-56,y+10.5);pdf.setTextColor(...rgb(t.main));pdf.setFont("helvetica","bold");pdf.text(`${g.pct}%`,W-28,y+10.5);y+=21}
if(plus){y+=5;pdf.setTextColor(...text);pdf.setFont("helvetica","bold");pdf.setFontSize(14);pdf.text("Documentazione fotografica · 10 foto",18,y);y+=8;const gapX=6,gapY=7,cols=2,cellW=(W-36-gapX)/2,cellH=32;for(let i=0;i<Math.min(10,photos?.length??0);i++){const col=i%2,row=Math.floor(i/2);let py=y+row*(cellH+gapY);let pageY=py;if(pageY+cellH+7>H-10){pdf.addPage();pdf.setFillColor(...navy);pdf.rect(0,0,W,22,"F");pdf.setTextColor(255,255,255);pdf.setFont("helvetica","bold");pdf.setFontSize(14);pdf.text("VeriDrive · Documentazione fotografica",18,14);py=32;}const x=18+col*(cellW+gapX);pdf.setFillColor(...pale);pdf.roundedRect(x,py,cellW,cellH,4,4,"F");const ph=photos?.[i] as Record<string,unknown>;const im=await imageData(db,String(ph.storage_path??""));if(im){const inset=1;const drawW=cellW-inset*2;const drawH=cellH-inset*2;pdf.addImage(im.data,im.format,x+inset,py+inset,drawW,drawH,undefined,"FAST");}else{pdf.setTextColor(...muted);pdf.setFontSize(8);pdf.text("Foto non disponibile",x+cellW/2,py+cellH/2,{align:"center"})}pdf.setTextColor(...text);pdf.setFont("helvetica","bold");pdf.setFontSize(7);pdf.text(`Foto ${i+1}`,x+2,py+cellH+4);}}
const bytes=pdf.output("arraybuffer");return new NextResponse(bytes,{status:200,headers:{"Content-Type":"application/pdf", "Content-Disposition":`attachment; filename="${certificate.public_code}${plus?"-PLUS":""}.pdf"`,"Cache-Control":"private,no-store"}})}catch(error){console.error("CUSTOMER_CERTIFICATE_PDF_ERROR",error);return NextResponse.json({error:error instanceof Error?error.message:"Impossibile generare il certificato."},{status:500})}}
